### ISSUE TITLE
helm upgrade error “Error: This command needs 2 arguments: release name, chart path”

### ISSUE THREAD

**Issue by vikasguptaanaplan** [Soluto/kamus#128]
I am getting an error in my kubernetes cluster while installing [kamus][1]   

    $ brew install kubernetes-helm

    $ helm init

$HELM_HOME has been configured at /Users/user/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!

    $ helm repo add soluto https://charts.soluto.io

"soluto" has been added to your repositories

    $ helm --debug upgrade --install soluto/kamus

[debug] Created tunnel using local port: '64252'

[debug] SERVER: "127.0.0.1:64252"

Error: This command needs 2 arguments: release name, chart path

Using helm version 2.13.1

    Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
    
    Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

[![enter image description here][2]][2]

I tried using the idea at [https://stackoverflow.com/questions/54190837/helm-install-in-kuberneres-error-this-command-needs-2-arguments-release-name][1] but it didn't help. Can you spot what I am doing wrong. Thank you.

  [1]: https://github.com/Soluto/kamus/tree/master/example
  [2]: https://i.stack.imgur.com/4hsxI.png

**Comment by omerlh** [comment]
Yes, you have a missing parameter - the name of the release which is requried on upgrade, but not on install. Look on the Getting Started [section](https://github.com/Soluto/kamus#getting-started) - this command should work:
```
helm upgrade --install kamus soluto/kamus
```

Let me know if this worked :)
