### ISSUE TITLE
Add yaml support to init container

### ISSUE THREAD

**Issue by yaron-idan** [Soluto/kamus#141]
Generating yaml configurations is becoming popular, in my case I found the need for it because that is the format [rtmbot](https://github.com/slackapi/python-rtmbot/blob/master/docs/example-config/rtmbot.conf) is expecting.

Adding support for this in Kamus can ease onboarding for many services, so I'll open a PR for it. 
WDYT?

**Comment by yaron-idan** [comment]
After some work, it seems supporting yaml for secrets encryption could miss some of the advantages of the format, since kubernetes configmaps cannot handle arrays or nested objects.
A better approach might be allowing users to supply Kamus with a template file.
This feature should include - 

- Adding a `template` option to the kamus cli
- Setting a clear standard for kamus secret placeholders in the template
- Allowing the init container to inject secrets into the template
WDYT @omerlh ?

**Comment by omerlh** [comment]
Sounds interesting - maybe as a refactoring of the current init container, with JSON as a template and allowing user-supplied template.
