### ISSUE TITLE
Add easier way to encrypt secrets

### ISSUE THREAD

**Issue by AvivRubys** [Soluto/kamus#152]
My main kamus pain point is that encrypting my secrets is a relatively manual process, which requires jumping between a browser and my cli and then copying and pasting stuff, and I find this to be very error prone and not great in terms of usability, especially if i need to encrypt a file through the dockerized kamus cli.
I've been thinking that adding a web page that you can use to encrypt secrets instead of the CLI might be convenient.
As a security measure we could require logging in every time someone enters the page, never cache the sessions locally, or use very short-lived cookies (5 or 10 minutes?)
What do you think?

**Comment by omerlh** [comment]
Are you referring to the authentication process? Web page will be a nice addition, while less secure - no support for pinning :) The encryption is just one way to protect the CLI, while it might be easier to make it available only internally.

**Comment by omerlh** [comment]
@AvivRubys can you add more information? Or can we close this issues?
