### ISSUE TITLE
type=KamusSecret  is NOT working.

### ISSUE THREAD

**Issue by shantanookirtane** [Soluto/kamus#196]
**Steps followed to install**

`helm init`
`kubectl apply -f helm_rbac.yml`
`helm init --upgrade --service-account tiller`
`helm upgrade --install kamus soluto/kamus`
`key=$(openssl rand -base64 256 | tr -d '\n')` - generate 256 bit key and base 64
`helm upgrade --install kamus soluto/kamus --set keyManager.AES.key=$key` - update the deployment to have this key

After this i was able to encrypt sample keys using encrypt API using below command

`kamus-cli encrypt --secret data1 --service-account kamus-sa --namespace default --kamus-url http://localhost:7000 --allow-insecure-url`

when i am putting this encrypted key within my "KamusSecret" type object and apply it using Kubectl command it is not getting created.

`kubectl get secrets --all-namespaces` does NOT show me the "KamusSecret" I created. 

Note: This setup works when I create a "ConfigMap" and store encrypted keys inside it. I am able see the ConfigMap is getting created and kamus-example application showing me decrypted values.

**Comment by omerlh** [comment]
I think this was fixed by #162, I just published a new chart with the latest kamus API version (Soluto/helm-charts#23) that should solve it. Can you try with the latest chart version?

**Comment by omerlh** [comment]
I think the issue was solved - @shantanookirtane can I close the issue?

**Comment by shantanookirtane** [comment]
Yes please. Thanks for your help
