### ISSUE TITLE
The documentation has incorrect reference of "KeyManager"

### ISSUE THREAD

**Issue by shantanookirtane** [Soluto/kamus#197]
https://kamus.soluto.io/docs/user/install/ - page has incorrect reference. 

helm upgrade --install kamus soluto/kamus --set **keyManager.AES.key**=$key

It should be

helm upgrade --install kamus soluto/kamus --set **keyManagement.AES.key**=$key

**Comment by omerlh** [comment]
Thanks for reporting this issue! I opened a PR to fix it...
