### ISSUE TITLE
Link to threat model is broken

### ISSUE THREAD

**Issue by ghostsquad** [Soluto/kamus#198]
I came here from reading the blog post, and it looks like the threat model link is broken. It's pointing to a `docs` top-level folder, which doesn't exist. Not sure where to find this.

**Comment by omerlh** [comment]
Thanks for raising the issue! Someone else also reported it on the blog, so I fixed the link. The threat model is now available [here](https://kamus.soluto.io/docs/threatmodeling/threats_controls/), as part of Kamus website.

**Comment by ghostsquad** [comment]
Thanks!
