### ISSUE TITLE
kamus-controller

### ISSUE THREAD

**Issue by Dhruva23** [Soluto/kamus#280]
Hi,

Getting below message after deploying kamus controller.

docker pull soluto/kamus

message: 'failed to start container "8467507c4fbf7739fe7900b6c0be2de2a140197e820ee4e7ef634acac6fe0279":
          Error response from daemon: OCI runtime create failed: container_linux.go:341:
          creating new parent process caused "container_linux.go:1713: running lstat
          on namespace path \"/proc/114448/ns/ipc\" caused \"lstat /proc/114448/ns/ipc:
          no such file or directory\"": unknown'

**Comment by omerlh** [comment]
Hey @Dhruva23 did you managed to find a solution?

**Comment by Dhruva23** [comment]
Hi Omer,

Yeah, thanks for your kind reply.

Thanks and Regards,
Dhruva
+91 9916092468

**Comment by omerlh** [comment]
Happy to hear so. Can I close the issue?

**Comment by Dhruva23** [comment]
Please close the issue.
