### ISSUE TITLE
Kamus CLI -u URL option should respect full path

### ISSUE THREAD

**Issue by pheonixtechnical** [Soluto/kamus#325]
**Describe the bug**
When using the -u or --kamus-url options, the path is ignored after the first slash (i.e after the top level domain). A call with '-u https://domain.com/security/kamus' goes to 'https://domain.com/api/v1/encrypt' rather than 'https://domain.com/security/kamus/api/v1/encrypt'.

**Versions used**
Kamus (API images): soluto/kamus:encryptor-0.4.4.1
Kamus CLI: 0.2.3
KMS provider: Azure KeyVault
Kubernetes flavour and version: Azure AKS - 1.14.3

**To Reproduce**
1. Call kamus-cli with 'https://domain.com/security/kamus' 

**Expected behavior**
The URL should be respected. A call with '-u https://domain.com/security/kamus' should go to 'https://domain.com/security/kamus/api/v1/encrypt'

**Comment by omerlh** [comment]
Thanks for reporting this issue! If you want to try and fix it, I think the bug is in this [line](https://github.com/Soluto/kamus/blob/9afe5cf3498b4bdd7013b2e725823e28742657eb/cli/lib/actions/encrypt.js#L148). I hope to have time to fix it later on this week, it seems a simple fix.

**Comment by omerlh** [comment]
We just published version 3.0.0 of the CLI with the fix, please test and let us know if it helped

**Comment by pheonixtechnical** [comment]
Thankyou for the fix, I shall try it today :)
