### ISSUE TITLE
Add support for IBM Cloud

### ISSUE THREAD

**Issue by gazzerman2** [Soluto/kamus#337]
**General remarks**

You support Azure from MS, GCE from Google and AWS, can you add IBM Cloud support too please?

**Comment by shaikatz** [comment]
We welcome PRs to support more KMS options.

**Comment by omerlh** [comment]
Especially because none of us ever worked with IBM cloud. AFAIK there is an API we can use for that, I'll be happy helping with the implemention.

**Comment by shaikatz** [comment]
Closing as stale, we can reopen if you would like to contribute it.
