### ISSUE TITLE
CLI example for encrypting secrets using azure keyvault

### ISSUE THREAD

**Issue by ncthbrt** [Soluto/kamus#356]
I've been struggling to encrypt secrets using Kamus and Azure Keyvault.
The main barrier I've been running into is what value `--auth-resource` must be and how to obtain it.

**Comment by omerlh** [comment]
Can you please share more information about the issue? Do you have an issue installing Kamus or encrypting?

**Comment by ncthbrt** [comment]
I have been able to setup Kamus on our AKS Cluster, however I'm struggling to encrypt keys.

**Comment by ncthbrt** [comment]
This is the following steps I've performed:

## Retrieved the pod name using kubectl:
```export POD_NAME=$(kubectl get pods --namespace default -l "app=kamus,release=kamus,component=encryptor" -o jsonpath="{.items[0].metadata.name}")```

## Started Port forwarding
`kubectl port-forward $POD_NAME 8080:9999`

## Attempted encryption:
```npx @soluto-asurion/kamus-cli encrypt -s "Super Secret" -a $k8sServiceAccount -u http://localhost:8080 --allow-insecure-url --auth-application $kamusAppId --auth-tenant $activeDirectoryTenantId --auth-resource ??? --namespace "default"
```

**Comment by omerlh** [comment]
Hey, sorry for the confusion. The `--auth-tenant` and `--auth-resource` are required only if you use AD authentication to protect Kamus encryptor. You can ignore them. The real issue is this:
```
Operation returned an invalid status code 'Forbidden'
```
Did you created correctly the service principal for Kamus, with the right permissions?

**Comment by ncthbrt** [comment]
Ah that makes sense. I will recheck those service principal settings and try set up kamus again.

**Comment by ncthbrt** [comment]
Thanks for the help. Got it encrypting!
