### ISSUE TITLE
Slack Invite Links have expired

### ISSUE THREAD

**Issue by ncthbrt** [Soluto/kamus#357]

**Comment by omerlh** [comment]
Just checked and it look like it working, can you please share the error message?

**Comment by ncthbrt** [comment]
Apologies for the lack of detail. I'm getting the following error message when clicking on the invite link: 

> This invite link is no longer active.
> Please check with the person who shared it with you to see if there's a new link available.

**Comment by omerlh** [comment]
Ok, I just created a new URL and opened a PR to fix all the links. Sorry for the inconvenience!
