### ISSUE TITLE
Improve AES encryption security by linking encryption/decryption to serviceaccount

### ISSUE THREAD

**Issue by tjololo** [Soluto/kamus#375]
**General remarks**
Running kamus in a on-prem deployment the only available option is AES. Secrets encrypted with AES can be decrypted if the user can deploy to one or more namespaces.
In a multitenant cluster this would render kamussecrets unsecure if the encypted data is shared in a public git repo

**Comment by omerlh** [comment]
One issue here is finding the right approach to do this. I'm not a cryptographic expert, but I guess we need some way to derive a new AES key for a specific service account. I do need to do some research...

**Comment by tjololo** [comment]
Not a cryptographic expert either. My first thoughts are to somehow combine the AES key and the serviceAccountId (<namespace>:<serviceaccount>) and generate a new key that can be reproduced if you know the namespace, serviceaccount and key. And then using this key to encrypt the secret.

**Comment by omerlh** [comment]
Yeah, that's what I'm also thinking. It's just important to ensure we know what we're doing otherwise, the encryption is compromised :)

**Comment by omerlh** [comment]
I asked on StackOverflow to get some advice: https://github.com/Soluto/kamus/pull/396

**Comment by omerlh** [comment]
The answer on StackOverflow proposed using HKDF algorithm, which seems a very good suggestion. Only problem HKDF is not supported currently on dotnet - see dotnet/corefx#42567, it's existing on dotnet core 5, released on November 2020.

**Comment by Yshayy** [comment]
Maybe it's possible to use https://gist.github.com/charlesportwoodii/09ffd6868c2a6e55826c4d5ebb509651 or other public .net OSS implementation until the MS one, it doesn't look too complex (size/external dependencies)
