### ISSUE TITLE
Unable to ignore newlines warning

### ISSUE THREAD

**Issue by wimo7083** [Soluto/kamus#435]
**Describe the bug**

This bug is related to kamus-cli only. 

I want to be able to encrypt a file that is available on localhost with CRLF in it. When I attempt the following below a warning from kamus prevents me. The warning should 

**Versions used**
Kamus (API images): latest
Kamus CLI: latest
Chart version: N/A
KMS provider: N/A
Kubernetes flavour and version: N/A

**To Reproduce**

Have kamus running in cluster. 
```bash
FILE=my_file_with_new_lines
DESTINATION_NAMESPACE='my_special_namespace'
SECRET_ACCOUNT=kamus-default
kubectl run --command=true  --restart=Never kamus-cli-$USER --image=soluto/kamus-cli -- sleep 1d
kubectl cp ${FILE} default/kamus-cli-$USER:/tmp/file
kubectl exec kamus-cli-$USER -- node lib/index.js encrypt --secret-file /tmp/file --kamus-url http://kamus-encryptor.default.svc.cluster.local/ --service-account ${SECRET_ACCOUNT} --namespace ${DESTINATION_NAMESPACE} --log-flag no-colorful
kubectl delete pod kamus-cli-$USER
```

**Expected behavior**

Encryption, without requiring interactive terminal, or a flag exists that allows you to ignore.

Ideally I'd also prefer a way to specify kamus to encode in some format prior to encrypint, and then when kamus decrypts have awareness of that encoding.  

```bash
[info  kamus-cli]: Encryption started...
[info  kamus-cli]: service account: kamus-default
[info  kamus-cli]: namespace: $$$$$$$$$
[warn  kamus-cli]: Auth options were not provided, will try to encrypt without authentication to kamus
? Secret contains newlines at index 31. Continue encrypting this secret? (y/%
>>> 
```

[Kamus slack]: (https://join.slack.com/t/k8s-kamus/shared_invite/enQtODA2MjI3MjAzMjA1LThlODkxNTg3ZGVmMjVkOTBhY2RmMmRjOWFiOGU2NzQ1ODU4ODNiMDJiZTE5ZTY4YmRiOTM3MjI0MDc0OGFkN2E)

**Comment by omerlh** [comment]
Your proposal makes sense, will you be able to open a PR? the flag should be simple as it's only the CLI, the encoding might be more complex.

**Comment by wimo7083** [comment]
Just noticing this. Thank you for doing that. I really appreciate it.
