### ISSUE TITLE
Kamus should “watch” for missing Secrets managed by KamusSecret

### ISSUE THREAD

**Issue by ragsonline** [Soluto/kamus#457]
In reference to #451 

Requesting the behaviour mentioned in the case #451 Kamus should “watch” for missing Secrets managed by KamusSecret.

By this, there is no need to delete KamusSecret and re-create whenever Kubernetes Secret Object is deleted.

**Comment by omerlh** [comment]
Giving this some thought, there are 2 ways to implement this:
- Watch all secrets in the cluster for Delete event - violate the least privilege. I don't want to give the controller permissions to get/list secrets in the cluster, it sounds too risky to me.
- Polling, e.g. once in a while (e.g. every 1 minute or so) re-create all the secrets that are owned by KamusSecrets (this is [godaddy external secret](https://github.com/godaddy/kubernetes-external-secrets) approach). While this is more secure, it creates unnecessary load on the API server (constantly creating secrets), which IMO does not worth it.

What do you think?

**Comment by ragsonline** [comment]
Yes i think Polling is the option to go .

or is it possible to re-create the KumusSecret or re-apply if already existing?? 
i.e. if some attempt to create KamusSecret that is already existing- instead of error out. apply the configuration that results in secret

**Comment by omerlh** [comment]
Well, this might allows an interesting privilege escalation issue - imagine you're a user who doesn't have permission to edit secrets (or KamusSecret). By creating a KamusSecret, you can edit existing secrets. I think it's safer to keep it that way.

We can add the polling - but it could create huge load on the API server, so if we do that it will be opt-in.

**Comment by micahlmartin** [comment]
@omerlh isn't this the way that most other controllers of CRD's work? Most I've seen all have a reconciliation loop that constantly checks if the resources still exist for the owning CRD.

**Comment by omerlh** [comment]
As I said, we can add polling, but I'm not sure it worth it - it requires additional permissions (list on all secrets) + add load on the API server. Wonder if we can write a small job that runs one in a while, check if all the secrets exist - and if not, re-create KamusSecret. This way you'll get this functionality as add-in. WDYT?

**Comment by titou10titou10** [comment]
> 
> 
> Giving this some thought, there are 2 ways to implement this:
> 
>     * Watch all secrets in the cluster for Delete event - violate the least privilege. I don't want to give the controller permissions to get/list secrets in the cluster, it sounds too risky to me.
> 
Instead of watching ***all*** secrets in ***any*** namespace, just watch secrets from explicitly listed namespaces (list held by an environment variable or by a config map) AND then secrets that have a specific label or annotation set by Kamus when it is generated (ie generated by kamus..)
This should narrow the list of watched secrets and should be acceptable as ony secrets manages by Kamus will be watched
WDYT?

**Comment by omerlh** [comment]
It does not matter - we still need RBAC permissions to watch secrets in all those namespaces.. AFAIK there is no way to limit with secrets a role has permissions to get..
