### ISSUE TITLE
Decryption doesn't fail when doing from unauthorized service account

### ISSUE THREAD

**Issue by vivekpd15** [Soluto/kamus#526]
**Describe the bug**

**Versions used**
Kamus (API images): 0.6.7.0
Kamus CLI: 0.3.0
Chart version: 0.4.8
KMS provider: AWS KMS
Kubernetes flavour and version: KOPS 1.15.12

**To Reproduce**
1. Encrypt a key with kamus secret with namespace A and service account B
2. Decrypt the key using namespace C and service account D

**Expected behavior**
Decryption should have failed. It successfully decrypted the key.

**Comment by omerlh** [comment]
Closing the issue as this is a security issue and should be reported according to our [security policy](https://github.com/Soluto/kamus/blob/master/security.md). Please do not use GitHub issue for security reporting.

**Comment by shaikatz** [comment]
Fixed with https://github.com/Soluto/kamus/commit/a864a3183ad5adc64c78b92cbbc11e4d5ad501a4
