### ISSUE TITLE
Allow AWS IRSA for EKS

### ISSUE THREAD

**Issue by ejimz** [Soluto/kamus#574]
I'm trying to use [aws IRSA](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) in my eks cluster and Kamus is not working, it looks like cant use  sts:AssumeRoleWithWebIdentity.
¿maybe the aws-sdk used by kamus is too old for this feature?

The error in the kamus-decryptor is the next:
https://pastebin.com/8zDLskAG

If I should provide more information about it just let me know.

**Comment by shaikatz** [comment]
I've checked and the version we are using is new enough to be able to use the AWS IRSA.
Can you print the encryptor/decryptor pods description?
Can you try to encrypt a secret first? does it succeed? 

Thanks for the info.

**Comment by ejimz** [comment]
If I try to encrypt a secret I get the next error message:
`[error kamus-cli]: Error while trying to encrypt with kamus: Encrypt request failed due to unexpected error. Status code: 500`

And the encryptor log is the next: https://pastebin.com/XbewUP5s 
the log above looks like is trying to assume the previous role assigned to the node, not the irsa role.


Encryptor pod description: https://pastebin.com/pSdBajYX
Decryptor description: https://pastebin.com/DSW5bbwx

**Comment by shaikatz** [comment]
Looking at the pod specs, everything looks like it configured correctly.
The only issues that might cause that is if the service cannot sucesfully assume the role you specified.
How did you create the IAM Role to ServiceAccount association? did you manually ran `eksctl iamserviceaccount` command?
You can reach me at kamus slack for faster troubleshooting (you can find the link to the slack in the readme)

**Comment by ejimz** [comment]
I created the cluster from terraform using the aws-eks official terraform module which include an option called "enable irsa" that create all the necessary things in eks and was. Also I've already migrated the aws cluster-autoscaler  with the same steps and it's working fine.

**Comment by shaikatz** [comment]
Maybe the terraform module you've used creates the IAM Role and the necessary trusted entities in AWS.
Can you check the `Trusted Relationships` tab from the `cluster-k8s-kamus` role in your AWS console?
It should specify there your cluster OIDC.

**Comment by ejimz** [comment]
Yes, that's correct, the trusted relationships is created fine with the cluster OIDC, and also the kamus serviceaccount is created with the role annotations.

**Comment by shaikatz** [comment]
Just noticed you are using outdated version of kamus which uses old AWS sdk.
Please update to use version 0.7.0.0 which should fix your problem.

**Comment by ejimz** [comment]
Cool! thank you!

In addition to that, we need to be able to add annotations to the kamus serviceaccount in order to set the IRSA roles

I've added a PR to solve this https://github.com/Soluto/helm-charts/pull/42

**Comment by shaikatz** [comment]
Thanks for adding that, you're definitely the first user using IRSA, and I'll be happy to know it's working :)

**Comment by ejimz** [comment]
Hi again,

I got now a different error:

{"Timestamp":"2020-08-25T07:33:39.1974470+00:00","Level":"Error","MessageTemplate":"Unhandled exception while processing request","Exception":"System.InvalidOperationException: Assembly AWSSDK.SecurityToken could not be found or loaded. This assembly must be available at runtime to use Amazon.Runtime.AssumeRoleAWSCredentials.\n ---> System.IO.FileNotFoundException: Could not load file or assembly 'AWSSDK.SecurityToken, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.\n\nFile name: 'AWSSDK.SecurityToken, Culture=neutral, PublicKeyToken=null'\n   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)\n   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)\n   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)\n   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)\n   at Amazon.Runtime.Internal.ServiceClientHelpers.GetSDKAssembly(String assemblyName)\n   at Amazon.Runtime.Internal.ServiceClientHelpers.LoadServiceConfigType(String assemblyName, String serviceConfigClassName)\n   at Amazon.Runtime.Internal.ServiceClientHelpers.CreateServiceConfig(String assemblyName, String serviceConfigClassName)\n   at Amazon.Runtime.AssumeRoleWithWebIdentityCredentials.CreateClient()\n\n\n   --- End of inner exception stack trace ---\n   at Amazon.Runtime.AssumeRoleWithWebIdentityCredentials.CreateClient()\n   at Amazon.Runtime.AssumeRoleWithWebIdentityCredentials.GenerateNewCredentialsAsync()\n   at Amazon.Runtime.RefreshingAWSCredentials.GetCredentialsAsync()\n   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Kamus.KeyManagement.AwsKeyManagement.GenerateEncryptionKey(String keyAlias) in /app/key-managment/AwsKeyManagement.cs:line 65\n   at Kamus.KeyManagement.AwsKeyManagement.Encrypt(String data, String serviceAccountId, Boolean createKeyIfMissing) in /app/key-managment/AwsKeyManagement.cs:line 33\n   at Kamus.Controllers.EncryptController.Encrypt(EncryptRequest body) in /app/encrypt-api/Controllers/EncryptController.cs:line 45\n   at lambda_method(Closure , Object )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\n   at App.Metrics.AspNetCore.Tracking.Middleware.ErrorRequestMeterMiddleware.Invoke(HttpContext context)\n   at Kamus.ErrorHandlingMiddleware.Invoke(HttpContext httpContext) in /app/encrypt-api/ErrorHandlingMiddleware.cs:line 31","Properties":{"SourceContext":"Kamus.ErrorHandlingMiddleware"}}


In addition to that I connected to the pod and tried to get the content of the token file and I could read the token perfectly.

**Comment by shaikatz** [comment]
Can you try replacing the encryptor image with `soluto/kamus:decryptor-fixirsa` which I've built from #576 and see if it helps?

**Comment by ejimz** [comment]
yes, using that image I can encrypt data properly using IRSA, but I realised that I only can encrypt data with the kamus-cli using "--service-account kamus", currently I'm using different pods with differents serviceaccounts.

If I understand correctly kamus-cli send a request to encrypt to kamus-encryptor which is a pod using the serviceaccount kamus that is allowed to handle AWS KMS using IRSA, is it correct or should I allow with IRSA each serviceaccount with encrypted keys?

**Comment by shaikatz** [comment]
You are correct, kamus-encryptor/kamus-decryptor are responsible for working with the KMS and they are the only ones who should have IRSA set for them.
What happens if you try to encrypt for different `service-account` parameter?

**Comment by shaikatz** [comment]
BTW - just released 0.7.1.0 (chart 0.4.13) which is the stable release of the image you've tested and confirmed working.

**Comment by ejimz** [comment]
If a try to encrypt a different service-account I get a "400" error.

"[error kamus-cli]: Error while trying to encrypt with kamus: Encrypt request failed due to unexpected error. Status code: 400"

**Comment by ejimz** [comment]
not sure if its related, but this is the log in the encryptor log

{"Timestamp":"2020-08-26T09:42:32.2794717+00:00","Level":"Information","MessageTemplate":"Executing endpoint '{EndpointName}'","Properties":{"EndpointName":"Kamus.Controllers.EncryptController.Encrypt (encrypt-api)","EventId":{"Name":"ExecutingEndpoint"},"SourceContext":"Microsoft.AspNetCore.Routing.EndpointMiddleware"}}
{"Timestamp":"2020-08-26T09:42:32.2795718+00:00","Level":"Information","MessageTemplate":"Route matched with {RouteData}. Executing controller action with signature {MethodInfo} on controller {Controller} ({AssemblyName}).","Properties":{"RouteData":"{action = \"Encrypt\", controller = \"Encrypt\"}","MethodInfo":"System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult] Encrypt(Kamus.Models.EncryptRequest)","Controller":"Kamus.Controllers.EncryptController","AssemblyName":"encrypt-api","EventId":{"Id":3,"Name":"ControllerActionExecuting"},"SourceContext":"Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker","ActionId":"2d295972-195d-47b2-a9fc-f9d74fd2cea5","ActionName":"Kamus.Controllers.EncryptController.Encrypt (encrypt-api)"}}
{"Timestamp":"2020-08-26T09:42:32.2813673+00:00","Level":"Information","MessageTemplate":"Encryption request started, SourceIP: {sourceIp}, ServiceAccount: {sa}, Namespace: {namespace}","Properties":{"sourceIp":"::ffff:127.0.0.1","sa":"default","namespace":"default","log_type":"audit","SourceContext":"Kamus.Controllers.EncryptController","ActionId":"2d295972-195d-47b2-a9fc-f9d74fd2cea5","ActionName":"Kamus.Controllers.EncryptController.Encrypt (encrypt-api)"}}
{"Timestamp":"2020-08-26T09:42:32.3192952+00:00","Level":"Information","MessageTemplate":"Executing ObjectResult, writing value of type '{Type}'.","Properties":{"Type":"System.String","EventId":{"Id":1,"Name":"ObjectResultExecuting"},"SourceContext":"Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor","ActionId":"2d295972-195d-47b2-a9fc-f9d74fd2cea5","ActionName":"Kamus.Controllers.EncryptController.Encrypt (encrypt-api)"}}
{"Timestamp":"2020-08-26T09:42:32.3196016+00:00","Level":"Information","MessageTemplate":"Executed action {ActionName} in {ElapsedMilliseconds}ms","Properties":{"ActionName":"Kamus.Controllers.EncryptController.Encrypt (encrypt-api)","ElapsedMilliseconds":39.9741,"EventId":{"Id":2,"Name":"ActionExecuted"},"SourceContext":"Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker","ActionId":"2d295972-195d-47b2-a9fc-f9d74fd2cea5"}}
{"Timestamp":"2020-08-26T09:42:32.3196603+00:00","Level":"Information","MessageTemplate":"Executed endpoint '{EndpointName}'","Properties":{"EndpointName":"Kamus.Controllers.EncryptController.Encrypt (encrypt-api)","EventId":{"Id":1,"Name":"ExecutedEndpoint"},"SourceContext":"Microsoft.AspNetCore.Routing.EndpointMiddleware"}}

**Comment by shaikatz** [comment]
I don't think those are the correct log lines, maybe you can jump into the [slack](https://join.slack.com/t/k8s-kamus/shared_invite/enQtODA2MjI3MjAzMjA1LThlODkxNTg3ZGVmMjVkOTBhY2RmMmRjOWFiOGU2NzQ1ODU4ODNiMDJiZTE5ZTY4YmRiOTM3MjI0MDc0OGFkN2E) and direct message me so we can solve it faster?

**Comment by ejimz** [comment]
As we talked in slack, the problem was that I tested it using the default serviceaccount, and its denied for security issues, I did the same with a different serviceaccount and it worked!
