### ISSUE TITLE
AssumeRoleWithWebIdentity cannot read WebIdentityTokenFile

### ISSUE THREAD

**Issue by ssedrick** [Soluto/kamus#588]
I've recently tried to deploy Kamus into an AWS environment. I've run into the following error:

> System.InvalidOperationException: A token could not be loaded from the WebIdentityTokenFile.
> ---> System.UnauthorizedAccessException: Access to the path '/var/run/secrets/eks.amazonaws.com/serviceaccount/token' is denied.
> ---> System.IO.IOException: Permission denied
>   --- End of inner exception stack trace ---
>   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
>   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
>   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
>   at Amazon.Runtime.AssumeRoleWithWebIdentityCredentials.GenerateNewCredentialsAsync()
>   --- End of inner exception stack trace ---

We are using service accounts with role arns as our means of assuming credentials.

### The bug
From what I can tell, the bug is that the secret token is not mounted in a readable manner. I think this might be an issue with the helm chart, but I'm not certain.

**Versions used**
Kamus (API images): 0.8.0.0
Kamus CLI: 0.3.0
Chart version: 0.4.14
KMS provider: AWS
Kubernetes flavour and version: AWS EKS 1.15

**To Reproduce**
1. Deploy the helm chart
   Use values liek:
```yaml
serviceAccount:
    annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXXXXX:role/some-role
```
3. Attempt to use `kamus-cli` to encrypt a secret.
4. `Kamus-cli` returns a 500 error and the encrypt pod will show this error.

**Expected behavior**
Encryption container should be able to pick up credentials correctly from the service account token.

**Comment by shaikatz** [comment]
You probably missed the section in the helm chart documentation regards using with EKS I am roles: https://github.com/Soluto/helm-charts/tree/master/charts/kamus#using-with-eks-iam-role-for-service-account
Let me know if it solved your issue.

**Comment by ssedrick** [comment]
@shaikatz That did resolve the issue. Thank you.
