### ISSUE TITLE
kubernetes secret objects made from KamusSecret should inherit labels and annotations, or provide a means of adding these to the derived Secret object

### ISSUE THREAD

**Issue by psiservices-tonywaters** [Soluto/kamus#593]
**General remarks**
There appears to be no way of adding labels or annotations to the Secret object created by KamusSecret

**Is your feature request related to a problem? Please describe.**
My Secret objects sometimes need annotations and/or labels - for example when using Helm version of Jenkins for Gitops, the Jenkins secret needs labels and annotations:
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "credentials from Kubernetes"

**Describe the solution you'd like**
KamusSecret has a method of passing labels and annotations on to the derived kubernetes Secret it creates

**Describe alternatives you've considered**
sealed-secret and helm-secret

**Comment by shaikatz** [comment]
Sounds like a great improvement. 
I will try to get to it, if you would like to create a PR yourself you are welcome.

**Comment by AmitBenAmi** [comment]
@psiservices-tonywaters We added a functionality to pass labels automatically from `KamusSecret` to `Secret` on `0.8.1.0`.
Also, it has a property called `propagateAnnotations` to pass the annotations as well (as they aren't passed automatically like labels) - Please see the documentation for full cover.
