### ISSUE TITLE
Refactor Helm chart note section

### ISSUE THREAD

**Issue by AleF83** [Soluto/kamus#76]

**Comment by omerlh** [comment]
All chart related issues should be filed under the [chart repository](https://github.com/Soluto/helm-charts). Also, please provide more details - what is missing?

**Comment by omerlh** [comment]
All chart related issues should be filed under the [chart repository](https://github.com/Soluto/helm-charts). Also, please provide more details - what is missing?

**Comment by AleF83** [comment]
New issue opened in [Soluto/helm-charts](https://github.com/Soluto/helm-charts)
