### ISSUE TITLE
Make CLI arguments order invariant

### ISSUE THREAD

**Issue by AleF83** [Soluto/kamus#77]
I suggest to use options instead of arguments in CLI encrypt command.
The encrypt command will be as following:
```
kamus-cli encrypt  \
   --secret super-secret \
   --service-account kamus-example-sa \
   --namespace default \
   --kamus-url <Kamus URL>
```
This approach will make the command line arguments order invariant and also we will be able to implement support for secret stored in file fixing #35.
For example for secret stored in file the command will be as following:
```
kamus-cli encrypt  \
   --secret-file /path/to/secret-file \
   --service-account kamus-example-sa \
   --namespace default \
   --kamus-url <Kamus URL>
```

I think it's more intuitive and self-describing command format.

**Comment by omerlh** [comment]
I think that the `--secret` is not required, the rest looks like a good proposal. Feel free to open a PR, we will appreciate the contribution :)

**Comment by shaikatz** [comment]
I actually like the `--secret` approach because as Alex said, it'll open a comfortable option to add the files support.

**Comment by omerlh** [comment]
I just think it is the only parameter that you expect to exist, but it's not critical. Both are good IMO

**Comment by AleF83** [comment]
I'll PR this issue
